name: STAGING - Build and Deploy

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "environment"
        required: true
        default: stage

env:
  GKE_PROJECT: ${{ secrets.GCP_PROJECT_ID_STG }}
  GCR_GKE_PROJECT: ibo-platform-components
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: asia-south1
  IMAGE: ibo-user-service
  REPOSITORY : us.gcr.io
  REGISTRY_HOSTNAME: us-docker.pkg.dev
  APP_NAME: ibo-user-service

jobs:
  node-build-deploy:
    runs-on: core-app

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GOOGLE_PRIVATE_KEY_STG }}

      - id: "get-credentials"
        uses: "google-github-actions/get-gke-credentials@v0"
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_STG }}
          project_id: ${{ secrets.GCP_PROJECT_ID_STG }}
          location: "asia-south1"

      - name: build-login-publish-docker image
        uses: ebomart/build-publish-docker-artifact@main
        with:
          registry_host: $REGISTRY_HOSTNAME
          repository: $REPOSITORY
          gke_project: $GCR_GKE_PROJECT
          image_name: $IMAGE
          google_private_key: ${{ secrets.GOOGLE_PRIVATE_KEY_STG }}
          sha: ${{ github.sha }}
          docker_build_args: "--build-arg NPM_TOKEN=$NPM_TOKEN"
          npm_token: ${{ secrets.NPM_TOKEN }}

      # Install helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        env:
          HELM_OPTS: --set-string environmentVariables.GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID_STG }}
        run: |
          helm upgrade --install --wait ibo-user-service deployment/charts/$APP_NAME --namespace user $HELM_OPTS --set image.tag=$GITHUB_SHA -f deployment/charts/config/values-staging.yaml
