name: FEATURE-BRANCH - Build and Test

on:
  push:
    branches-ignore:
      - main

env:
  GKE_PROJECT: ${{ secrets.GCP_PROJECT_ID_DEV }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: asia-south1
  IMAGE: ibo-user-service
  REPOSITORY : us.gcr.io
  REGISTRY_HOSTNAME: us-docker.pkg.dev
  APP_NAME: ibo-user-service

jobs:
  node-build-deploy:
    runs-on: core-app

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Dockerfile Lint
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile

      - name: Get the deployment file
        run: helm template $IMAGE deployment/charts/$IMAGE -f deployment/charts/$IMAGE/values.yaml --output-dir opa

      - name: OPA Kubernetes
        uses: ebomart/opa-kubernetes@v2.1.16
        with:
          file: opa/ibo-user-service/templates/deployment.yaml

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'npm'
          # cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ebomart'

      - name: Update to npm 8.x
        run: npm i -g npm@8

      # - name: Remove .npmrc
      #   run: rm -rf .npmrc

      - name: Install dependencies
        run: npm install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Restore .npmrc
      #   run: git checkout .npmrc

      - name: Run post install scripts
        run: npm rebuild && npm run prepare --if-present

      - name: Code Linting
        run: npm run lint

      - name: Unit Test
        run: npm run test:unit

      - name: Dependency Checks
        run: npm audit
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1.0.0
        with:
          projectBaseDir: .      
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time
        timeout-minutes: 5
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
